from django.urls import path
from . import views


urlpatterns = [
    path('interestings/', views.IntererstingView.as_view(), name='intererstings'),
    path('checkuser/', views.CheckUserView.as_view(), name='checkuser'),
    path('email/', views.EmailVerificationView.as_view(), name='email'),
    path('emailverify/', views.VerifyEmailView.as_view(), name='emailverify'),
    path('register/', views.UserRegistration.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('rolesetting/', views.UserRoleView.as_view(), name='rolesetting'),
    path('setting/', views.SettingView.as_view(), name='setting'),
    path('notificationsetting/', views.UserNotificationSettingView.as_view(), name='notificationsetting'),
    path('changepassword/', views.UserChangePasswordView.as_view(), name='changepassword'),
    path('resetrequest/', views.PasswordResetRequestView.as_view(), name='resetrequest'),
    path('resetpassword/', views.PasswordResetView.as_view(), name='resetpassword'),
    path('resetpassworddone/', views.PasswordResetDoneView.as_view(), name='resetpassworddone'),
    path('logout/', views.UserLogoutView.as_view(), name ='logout'),
    path('addpost/', views.PostView.as_view(), name='addpost'),
    path('posts/', views.PostsView.as_view(), name='posts'),
    path('post/<int:id>/', views.PostView.as_view(), name='post'),
    path('postlike/<int:id>/', views.PostLikesView.as_view(), name = 'postlike'),
    path('postdislike/<int:id>/', views.PostDislikesView.as_view(), name = 'postdislike'),
    path('postcomment/<int:id>/', views.PostCommentView.as_view(), name = 'postcomment'),
    path('addbook/', views.AddNewBooksViews.as_view(), name = 'addbook'),
    path('my-books-list/', views.MyBookListsViews.as_view(), name = 'my-books-list'),
    path('my-book-detail/<int:id>/', views.MyBookDetailViews.as_view(), name = 'my-book-detail'),
    path('books-list/<int:id>/', views.BookListsViews.as_view(), name = 'books-list'),
    path('book-detail/<int:id>/', views.BookDetailViews.as_view(), name = 'book-detail'),
    # path('sendfriendrequest/<int:id>/', views.SendFriendRequest.as_view(), name='sendfriendrequest'),
    # path('acceptfriendrequest/<int:id>/', views.AcceptFriendRequest.as_view(), name='acceptfriendrequest'),
    # path('declinefriendrequest/<int:id>/', views.DeclineFriendRequest.as_view(), name='declinefriendrequest'),
    # path('unfriend/<int:id>/', views.UnfriendView.as_view(), name='unfriend'),
    # path('sentrequests/', views.ViewSentRequests.as_view(), name='sentrequests'),
    # path('receivedrequests/', views.ViewRecievedRequests.as_view(), name='receivedrequests'),
    # path('tvsetting/', views.TVSettingView.as_view(), name='tvsetting'),
    # path('tvchannels/', views.TVChannelsView.as_view(), name='tvchannels'),
    # path('tvchannel/<int:id>/', views.TVChannelView.as_view(), name='tvchannel'),
    # path('tvchannelcomments/<int:id>/', views.TVChannelCommentView.as_view(), name='tvchannelcomments'),
    path('notifications/', views.NotificationsView.as_view(), name='notifications'),
    path('notificationscount/', views.NotificationsCountView.as_view(), name='notificationscount'),
    path('notification/<int:id>/', views.NotificationDetailView.as_view(), name='notification'),
    path('removenotification/<int:id>/', views.NotificationRemoveView.as_view(), name='removenotification'),
    path('addfollower/<int:id>/', views.AddFollower.as_view(), name='addfollower'),
    path('addfollowers/', views.AddFollowers.as_view(), name='addfollowers'),
    path('removefollower/<int:id>/', views.RemoveFollower.as_view(), name='removefollower'),
    path('user/<int:id>/', views.UserView.as_view(), name='user'),
    path('popularlists/', views.PopularLists.as_view(), name='popularusers'),
    path('liveusers/', views.LiveUsers.as_view(), name='liveusers'),
    path('followers/<int:id>/', views.FollowersList.as_view(), name='followers'),
    path('myfollowers/', views.MyFollowersList.as_view(), name='myfollowers'),
    path('help/', views.HelpView.as_view(), name='help'),
    path('helpdetail/<int:id>/', views.HelpDetailView.as_view(), name='helpdetail'),
    path('profile-report/', views.ProfileReport.as_view(), name='profile-report'),
    path('my-stream/', views.StreamView.as_view(), name='my-stream'),
]